version: '2'

services:
  aspnet-core-docker-debug:
    image: aspnet-core-docker-debug:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
